### ISSUE TITLE
codepen.io refused to connect

### ISSUE THREAD

**Issue by oscar8a** [learn-co-curriculum/js-strings-and-numbers-lab#12]
![Capturecodepen](https://user-images.githubusercontent.com/5483769/55636568-1a063680-5791-11e9-925a-019e7c1705c9.JPG)

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration
in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙

**Comment by Donnadieu** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Comment by oscar8a** [comment]
Thank you for checking into this, I no longer use the computer I used when this happened. I just tried using now and it shows up, so there isn't an issue anymore if there was. 😁
