### ISSUE TITLE
Extra Credit: Adding an additional employer Instructions Clarification

### ISSUE THREAD

**Issue by ryerayne** [learn-co-curriculum/js-strings-and-numbers-lab#5]
It would help to clarify the instructions for step #4: Extra Credit: Can you add an additional employer? 

I just edited the HTML to add an additional employer- I didn't think about using the Javascript. 

Instead, it could say "Extra Credit: Can you add an additional employer using Javascript?"

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration
in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙
