### ISSUE TITLE
practicing conditional statements lab

### ISSUE THREAD

**Issue by swarbrick85** [learn-co-curriculum/js-strings-and-numbers-lab#8]
says to open the IDE but there's no button to do so

**Comment by Donnadieu** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
